name: Reusable Dotnet Workflow

inputs:
  command:
    required: true
    type: string
  projects:
    required: true
    type: string
  arguments:
    required: false
    type: string
  restoreArguments:
    required: false
    type: string
  solution:
    required: true
    type: string
  configuration: 
    required: true
    type: string

runs:
  using: 'composite'  
  steps:
  
    - name: Validate Solution Path
      shell: pwsh
      run: |
        if (!(Test-Path "${{ inputs.solution }}")) {
          Write-Error "Solution file not found at path: ${{ inputs.solution }}"
          exit 1
        }

    - name: Restore Dependencies
      shell: pwsh
      run: |
        dotnet restore ${{ inputs.solution }} ${{ inputs.restoreArguments }}

    - name: Build
      shell: pwsh
      run: |
        dotnet build ${{ inputs.solution }} --configuration ${{ inputs.configuration }} ${{ inputs.arguments }}
